### ISSUE TITLE
Deployment of a new cluster unexpectedly created two master

### ISSUE THREAD

**Issue by planetf1** [civo/kube100#10] opened 2019-11-11 10:17 UTC
Unfortunately I've subsequently deleted this cluster, but I was surprised to see two master's showing in this configuration - I've not seen it before, so wondered if something may have gone wrong.

I understand we may need to close since no further inspection may be possible
```
➜  ~ civo k8s show web3
                ID : e56183fd-bf7b-4b99-ae10-05d21bc6c5d3
              Name : web3
           # Nodes : 3
              Size : g2.small
            Status : ACTIVE
           Version : 0.10.0
      API Endpoint : https://91.211.153.178:6443
      DNS A record : e56183fd-bf7b-4b99-ae10-05d21bc6c5d3.k8s.civo.com
                     *.e56183fd-bf7b-4b99-ae10-05d21bc6c5d3.k8s.civo.com

Nodes:
+------------------+-----------------+--------+
| Name             | IP              | Status |
+------------------+-----------------+--------+
| kube-master-3184 | 91.211.153.178  | ACTIVE |
| kube-master-fa7e | 185.136.235.124 | ACTIVE |
| kube-node-99f8   | 91.211.153.63   | ACTIVE |
+------------------+-----------------+--------+

Installed marketplace applications:
+---------+-----------+-----------+--------------+
| Name    | Version   | Installed | Category     |
+---------+-----------+-----------+--------------+
| Traefik | (default) | Yes       | architecture |
+---------+-----------+-----------+--------------+
```

**Comment by shaunmclernon** [comment] 2019-11-14 14:38
I have had the same issue, although in my case its only created two masters.

```
civo version
You are running the current v0.5.6 of Civo CLI
```

Cluster created as follows
```
civo k3s create --remove-applications=traefik --nodes=2 --wait openfaas
```

When completed its showing 2 masters (and still says its installing).

```
civo k3s show openfaas
                ID : 01e35ba4-d891-4c48-a471-0caf4ad409b2
              Name : openfaas
           # Nodes : 2
              Size : g2.medium
            Status : INSTALLING
           Version : 0.9.1
      API Endpoint : https://91.211.153.6:6443
      DNS A record : 01e35ba4-d891-4c48-a471-0caf4ad409b2.k8s.civo.com
                     *.01e35ba4-d891-4c48-a471-0caf4ad409b2.k8s.civo.com

Nodes:
+------------------+----------------+--------+
| Name             | IP             | Status |
+------------------+----------------+--------+
| kube-master-801c | 91.211.153.6   | ACTIVE |
| kube-master-8f6f | 91.211.152.214 | ACTIVE |
+------------------+----------------+--------+
```

**Comment by andyjeffries** [comment] 2019-11-14 14:39
OK, thanks guys. I'll get in to this properly early next week - it's a hard one as it doesn't happen often/every time.

**Comment by shaunmclernon** [comment] 2019-11-14 14:45
No worries, I was just giving some feedback (not a blocker for me at this time).

**Comment by andyjeffries** [comment] 2019-11-14 14:45
I appreciate it 👍 !

**Comment by andyjeffries** [comment] 2019-12-06 14:46
I believe this is fixed now (was a race condition I believe). Have been unable to reproduce since I fixed it... yesterday(?).

**Closed as completed by andyjeffries** 2019-12-06 14:46 UTC
